allowBuilds:
  cbor-extract: false
  esbuild: false
minimumReleaseAgeExclude:
  - '@inkandswitch/patchwork-comments@0.1.2'
  - '@inkandswitch/patchwork-providers-solid@0.1.3'
  - '@inkandswitch/patchwork-providers@0.1.2'
