import "./global.css";

declare const __KEYHIVE__: boolean;

import { bootPatchworkSite } from "@inkandswitch/patchwork-bootloader/site";

// patchwork-base is served as a fully static deployment: the default tool
// bundle is a static JSON manifest (generated by `scripts/build-static.mjs`)
// served from this same origin, alongside the tools' compiled JS under
// `/tools/`. No Automerge module-settings document is required to boot.
//
// You can still mix in Automerge-hosted tool sets — or an entirely different
// manifest — at runtime by setting `localStorage.defaultToolsUrl` to either an
// `automerge:` URL or another manifest URL. Each user's personal Automerge
// module-settings doc (created by the frame) continues to layer on top, so
// individual tools can come from either deployment target.
await bootPatchworkSite({
  defaultModules: ["/modules.json"],
  accountStorageKey: "patchworkBaseAccountUrl",
  titleSuffix: "patchwork-base",
  keyhive: __KEYHIVE__,
});
