allowBuilds:
  cbor-extract: true
  core-js: true
  esbuild: true
minimumReleaseAgeExclude:
  - '@inkandswitch/patchwork-bootloader@0.2.8'
  - '@inkandswitch/patchwork-elements@2.0.0'
overrides:
  "@inkandswitch/patchwork-providers": "0.2.2"
  "@inkandswitch/patchwork-providers-react": "0.2.2"
